// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Utilities.Configuration;
//
//    var configurationValues = ConfigurationValues.FromJson(jsonString);
using System.Collections.Generic;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using J = Newtonsoft.Json.JsonPropertyAttribute;
using R = Newtonsoft.Json.Required;

namespace Utilities.Configuration
{
    public partial class ConfigurationValues
    {
        [JsonConstructor]
        public ConfigurationValues(MedalsConfig medals, WavesConfig waves, SpawnersConfig spawners, GameEntitiesConfig gameEntities)
        {
            Medals = medals;
            Waves = waves;
            Spawners = spawners;
            GameEntities = gameEntities;
        }

        [J("Medals", Required = R.Always)] public MedalsConfig Medals { get; }
        [J("Waves", Required = R.Always)] public WavesConfig Waves { get; }
        [J("Spawners", Required = R.Always)] public SpawnersConfig Spawners { get; }
        [J("GameEntities", Required = R.Always)] public GameEntitiesConfig GameEntities { get; }
    }

    public partial class GameEntitiesConfig
    {
        [JsonConstructor]
        public GameEntitiesConfig(PlayerShipsConfig ships, PowerUpsConfig powerUps, BulletsConfig bullets, EnemiesConfig enemies)
        {
            PlayerShips = ships;
            PowerUps = powerUps;
            Bullets = bullets;
            Enemies = enemies;
        }

        [J("Ships", Required = R.Always)] public PlayerShipsConfig PlayerShips { get; }
        [J("PowerUps", Required = R.Always)] public PowerUpsConfig PowerUps { get; }
        [J("Bullets", Required = R.Always)] public BulletsConfig Bullets { get; }
        [J("Enemies", Required = R.Always)] public EnemiesConfig Enemies { get; }
    }
    public partial class PowerUpsConfig
    {
        [JsonConstructor]
        public PowerUpsConfig(PowerUpConfig extraLifePowerUp, EffectPowerUpConfig freezerPowerUp)
        {
            ExtraLifePowerUp = extraLifePowerUp;
            FreezerPowerUp = freezerPowerUp;
        }

        [J("ExtraLifePowerUp", Required = R.Always)] public PowerUpConfig ExtraLifePowerUp { get; }
        [J("FreezerPowerUp", Required = R.Always)] public EffectPowerUpConfig FreezerPowerUp { get; }
    }

    public class PowerUpConfig
    {
        [JsonConstructor]
        public PowerUpConfig(float lifeDuration)
        {
            LifeDuration = lifeDuration;
        }

        [J("LifeDuration", Required = R.Always)] public float LifeDuration { get; }
    }

    public class EffectPowerUpConfig : PowerUpConfig
    {
        [JsonConstructor]
        public EffectPowerUpConfig(float effectDuration, float lifeDuration) : base(lifeDuration)
        {
            EffectDuration = effectDuration;
        }

        [J("EffectDuration", Required = R.Always)] public float EffectDuration { get; }
    }

    public partial class BulletsConfig
    {
        [JsonConstructor]
        public BulletsConfig(LaserBulletConfig laserBullet)
        {
            LaserBullet = laserBullet;
        }

        [J("LaserBullet", Required = R.Always)] public LaserBulletConfig LaserBullet { get; }
    }
    public partial class LaserBulletConfig
    {
        [JsonConstructor]
        public LaserBulletConfig(float bulletDamage, float bulletLifeDuration)
        {
            BulletDamage = bulletDamage;
            BulletLifeDuration = bulletLifeDuration;
        }

        [J("BulletDamage", Required = R.Always)] public float BulletDamage { get; }
        [J("BulletLifeDuration", Required = R.Always)] public float BulletLifeDuration { get; }
    }

    public class AliveEntityConfig
    {
        [JsonConstructor]
        public AliveEntityConfig(float maxHitpoints, float initialHitpoints, float baseDamage, float damageCooldownDuration)
        {
            MaxHitpoints = maxHitpoints;
            InitialHitpoints = initialHitpoints;
            BaseDamage = baseDamage;
            DamageCooldownDuration = damageCooldownDuration;
        }

        [J("MaxHitpoints", Required = R.Always)] public float MaxHitpoints { get; }
        [J("InitialHitpoints", Required = R.Always)] public float InitialHitpoints { get; }
        [J("BaseDamage", Required = R.Always)] public float BaseDamage { get; }
        [J("DamageCooldownDuration", Required = R.Always)] public float DamageCooldownDuration { get; }
    }

    public class ShipConfig : AliveEntityConfig
    {
        [JsonConstructor]
        public ShipConfig(float rotationSpeed, float thrustAmount, Dictionary<string, GunConfig> guns, float maxHitpoints, float initialHitpoints, float baseDamage, float damageCooldownDuration) : base(maxHitpoints, initialHitpoints, baseDamage, damageCooldownDuration)
        {
            RotationSpeed = rotationSpeed;
            ThrustAmount = thrustAmount;
            Guns = guns;
        }

        [J("RotationSpeed", Required = R.Always)] public float RotationSpeed { get; }
        [J("ThrustAmount", Required = R.Always)] public float ThrustAmount { get; }
        [J("Guns", Required = R.Always)] public Dictionary<string, GunConfig> Guns { get; }
    }

    public class GunConfig
    {
        [JsonConstructor]
        public GunConfig(float bulletInitialImpulseMagnitude, float shootCooldownDuration)
        {
            BulletInitialImpulseMagnitude = bulletInitialImpulseMagnitude;
            ShootCooldownDuration = shootCooldownDuration;
        }

        [J("BulletInitialImpulseMagnitude", Required = R.Always)] public float BulletInitialImpulseMagnitude { get; }
        [J("ShootCooldownDuration", Required = R.Always)] public float ShootCooldownDuration { get; }
    }

    public partial class MedalsConfig
    {
        [JsonConstructor]
        public MedalsConfig(float minLifeDuration, float maxLifeDuration)
        {
            MinLifeDuration = minLifeDuration;
            MaxLifeDuration = maxLifeDuration;
        }

        [J("MinLifeDuration", Required = R.Always)] public float MinLifeDuration { get; }
        [J("MaxLifeDuration", Required = R.Always)] public float MaxLifeDuration { get; }
    }

    public partial class ConfigurationValues
    {
        public static ConfigurationValues FromJson(string json) => JsonConvert.DeserializeObject<ConfigurationValues>(json, Utilities.Configuration.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ConfigurationValues self) => JsonConvert.SerializeObject(self, Utilities.Configuration.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
